# Generated by Django 6.0.3 on 2026-03-24 14:45

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_scelto', models.CharField(default='4-3-3')),
            ],
        ),
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('squadra_reale', models.CharField(max_length=100)),
                ('data_nascita', models.DateField()),
                ('ruolo', models.CharField(choices=[('portiere', 'P'), ('difensore', 'D'), ('centrocampista', 'C'), ('attaccante', 'A')])),
                ('altezza', models.IntegerField(validators=[django.core.validators.MinValueValidator(140), django.core.validators.MaxValueValidator(230)])),
                ('piede_preferito', models.CharField(choices=[('destro', 'Dx'), ('sinistro', 'Sx')])),
                ('nazionalità', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='foto/user.png', upload_to='foto/')),
                ('descrizione', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Giornata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giornata', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GiocatoreSchierato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolare', models.BooleanField(default=False)),
                ('ordine_panchina', models.PositiveIntegerField(default=0)),
                ('formazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.formazione')),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.giocatore')),
                ('giocatore_sostituito_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switch_ricevuti', to='game.giocatore')),
            ],
        ),
        migrations.AddField(
            model_name='formazione',
            name='giornata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.giornata'),
        ),
        migrations.CreateModel(
            name='Lega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('partecipanti', models.IntegerField(choices=[(4, '4'), (6, '6'), (8, '8'), (10, '10'), (12, '12'), (14, '14'), (16, '16')])),
                ('password', models.CharField(max_length=128)),
                ('crediti', models.IntegerField(choices=[(100, '100'), (250, '250'), (500, '500'), (1000, '1000')])),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImpostazioniRosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_portieri', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('numero_difensori', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(25)])),
                ('numero_centrocampisti', models.IntegerField(validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(25)])),
                ('numero_attaccanti', models.IntegerField(validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(25)])),
                ('lega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.lega')),
            ],
        ),
        migrations.CreateModel(
            name='ImpostazioniPunteggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soglia_primo_gol', models.FloatField(default=66.0)),
                ('punti_gol_successivi', models.FloatField(default=6.0)),
                ('modificatore_difesa', models.BooleanField(default=False)),
                ('lega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.lega')),
            ],
        ),
        migrations.CreateModel(
            name='ImpostazioniMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduli', multiselectfield.db.fields.MultiSelectField(choices=[('3-4-3', '3-4-3'), ('3-5-2', '3-5-2'), ('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('4-5-1', '4-5-1'), ('5-3-2', '5-3-2'), ('5-4-1', '5-4-1')], max_length=41)),
                ('posti_panchina', models.IntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(15)])),
                ('tipo_panchina', models.CharField(choices=[('libera', 'Libera'), ('vincolata_ruolo', 'Vincolata al ruolo')])),
                ('num_sostituzioni', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tipo_switch', models.CharField(choices=[('nessuno', 'Nessuno'), ('base', 'Base'), ('plus', 'Plus')], default='nessuno')),
                ('lega', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.lega')),
            ],
        ),
        migrations.CreateModel(
            name='BonusMalus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('portiere', 'P'), ('difensore', 'D'), ('centrocampista', 'C'), ('attaccante', 'A')])),
                ('valore_gol', models.FloatField(default=3.0)),
                ('gol_subito', models.FloatField(default=1.0)),
                ('valore_assist', models.FloatField(default=1.0)),
                ('valore_ammonizione', models.FloatField(default=0.5)),
                ('rigori_segnati', models.FloatField(default=3.0)),
                ('rigori_sbagliati', models.FloatField(default=3.0)),
                ('rigori_parati', models.FloatField(default=3.0)),
                ('valore_espulsione', models.FloatField(default=1.0)),
                ('contributi_al_gol', models.FloatField(default=0)),
                ('assist_soft', models.FloatField(default=1.0)),
                ('assist_gold', models.FloatField(default=1.0)),
                ('autogol', models.FloatField(default=2.0)),
                ('gol_pareggio', models.FloatField(default=0)),
                ('gol_vittoria', models.FloatField(default=0)),
                ('porta_inviolata', models.FloatField(default=1)),
                ('player_of_the_match', models.FloatField(default=0)),
                ('lega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lega')),
            ],
        ),
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, default='logo/logo.webp', upload_to='logo/')),
                ('lega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lega')),
                ('primo_allenatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allenatore_principale', to='accounts.profile')),
                ('rosa', models.ManyToManyField(to='game.giocatore')),
                ('secondo_allenatore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_allenatore', to='accounts.profile')),
            ],
        ),
        migrations.AddField(
            model_name='formazione',
            name='squadra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.squadra'),
        ),
        migrations.CreateModel(
            name='Statistiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.FloatField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3'), (3.5, '3.5'), (4, '4'), (4.5, '4.5'), (5, '5'), (5.5, '5.5'), (6, '6'), (6.5, '6.5'), (7, '7'), (7.5, '7.5'), (8, '8'), (8.5, '8.5'), (9, '9'), (9.5, '9.5'), (10, '10')])),
                ('gol_fatti', models.PositiveIntegerField(default=0)),
                ('assist', models.PositiveIntegerField(default=0)),
                ('ammonizioni', models.PositiveIntegerField(default=0)),
                ('espulsioni', models.PositiveIntegerField(default=0)),
                ('gol_subiti', models.PositiveIntegerField(default=0)),
                ('rigori_parati', models.PositiveIntegerField(default=0)),
                ('assist_soft', models.PositiveIntegerField(default=0)),
                ('assist_gold', models.PositiveIntegerField(default=0)),
                ('contributi_al_gol', models.PositiveIntegerField(default=0)),
                ('gol_pareggio', models.PositiveIntegerField(default=0)),
                ('gol_vittoria', models.PositiveIntegerField(default=0)),
                ('player_of_the_match', models.BooleanField(default=False)),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.giocatore')),
                ('giornata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.giornata')),
            ],
        ),
    ]
