# Generated by Django 6.0.3 on 2026-04-08 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lega',
            name='membri',
            field=models.ManyToManyField(related_name='membro_lega', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lega',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatore_lega', to=settings.AUTH_USER_MODEL),
        ),
    ]
