# Generated by Django 6.0.3 on 2026-03-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vittorie', models.IntegerField(default=0)),
                ('pareggi', models.IntegerField(default=0)),
                ('sconfitte', models.IntegerField(default=0)),
                ('gol_fatti', models.IntegerField(default=0)),
                ('gol_subiti', models.IntegerField(default=0)),
                ('differenza_reti', models.IntegerField(default=0)),
                ('punti', models.IntegerField(default=0)),
                ('punti_totali', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PartitaLega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punti_casa', models.FloatField(default=0.0)),
                ('punti_ospite', models.FloatField(default=0.0)),
                ('gol_casa', models.IntegerField(default=0)),
                ('gol_ospite', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='giocatoreschierato',
            name='titolare',
        ),
        migrations.AddField(
            model_name='giocatoreschierato',
            name='stato',
            field=models.CharField(choices=[('titolare', 'Titolare'), ('panchina', 'Panchina')], default='titolare'),
        ),
        migrations.AddField(
            model_name='giornata',
            name='calcolata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giornata',
            name='finita',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statistiche',
            name='fantavoto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddConstraint(
            model_name='formazione',
            constraint=models.UniqueConstraint(fields=('squadra', 'giornata'), name='unique_formazione_per_squadra_per_giornata'),
        ),
        migrations.AddField(
            model_name='classifica',
            name='lega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lega'),
        ),
        migrations.AddField(
            model_name='classifica',
            name='squadra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.squadra'),
        ),
        migrations.AddField(
            model_name='partitalega',
            name='giornata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.giornata'),
        ),
        migrations.AddField(
            model_name='partitalega',
            name='squadra_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadra_casa', to='game.squadra'),
        ),
        migrations.AddField(
            model_name='partitalega',
            name='squadra_ospite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadra_ospite', to='game.squadra'),
        ),
    ]
