# Generated by Django 6.0.3 on 2026-04-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_lega_membri_alter_lega_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lega',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
