# Generated by Django 6.0.3 on 2026-03-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_classifica_partitalega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornata',
            name='orario_inizio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
