# Generated by Django 6.0.3 on 2026-04-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0003_alter_lega_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadra',
            name='lega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre', to='game.lega'),
        ),
        migrations.CreateModel(
            name='InvitoSquadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('nessun_invito', 'Nessun invito'), ('inviato', 'Inviato'), ('accettato', 'Accettato'), ('rifiutato', 'Rifiutato')], default='nessun_invito')),
                ('squadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.squadra')),
                ('utente_invitato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
