# Generated by Django 6.0.3 on 2026-04-22 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0004_alter_squadra_lega_invitosquadra'),
    ]

    operations = [
        migrations.AddField(
            model_name='giornata',
            name='lega',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lega'),
        ),
        migrations.AlterField(
            model_name='invitosquadra',
            name='stato',
            field=models.CharField(choices=[('inviato', 'Inviato'), ('accettato', 'Accettato'), ('rifiutato', 'Rifiutato')], default='inviato'),
        ),
        migrations.AddConstraint(
            model_name='invitosquadra',
            constraint=models.UniqueConstraint(fields=('squadra', 'utente_invitato'), name='unique_utente_invitato_per_squadra'),
        ),
    ]
