# Generated by Django 6.0.3 on 2026-04-22 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_giornata_lega_alter_invitosquadra_stato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornata',
            name='lega',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.lega'),
        ),
    ]
