# Generated by Django 6.0.3 on 2026-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_giornata_lega'),
    ]

    operations = [
        migrations.AddField(
            model_name='lega',
            name='calendario_generato',
            field=models.BooleanField(default=False),
        ),
    ]
