# Generated by Django 6.0.3 on 2026-04-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_lega_calendario_generato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giornata',
            name='lega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lega'),
        ),
    ]
